version: "3"
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mariadb/init/:/docker-entrypoint-initdb.d/
      # Use a volume for MySQL data
      - mysql_data:/var/lib/mysql/
      # Or mount MySQL data directly
      #- ./mysql_data/:/var/lib/mysql/
    command: 
      - --max_allowed_packet=1024M # Set max_allowed_packet to 256M (or any other value)

# Comment out if you want to mount data directly
volumes:
  mysql_data:
