CREATE DATABASE IF NOT EXISTS REPLACE_DATABASE_NAME;
CREATE USER IF NOT EXISTS 'REPLACE_USERNAME'@'REPLACE_HOSTNAME' IDENTIFIED BY 'REPLACE_PASSWORD';
GRANT REPLACE_PRIVILEGES ON REPLACE_DATABASE_NAME.REPLACE_DATABASE_TABLES TO 'REPLACE_USERNAME'@'REPLACE_HOSTNAME';
FLUSH PRIVILEGES;
